### ISSUE TITLE
Client Event Emission Failing

### ISSUE THREAD

**Issue by 4meta5** [sunshine-protocol/sunshine-node#95]
I have a feeling that I am not using the subxt macro correctly. In particular, I suspect that there are some naming conventions that I am not following. cc @dvc94ch 

A recent commit will show the often return `EventNotFound` error if you run `cargo run --example org` in the `client` directory while the node is running...

```rust
    Finished dev [unoptimized + debuginfo] target(s) in 2m 28s
     Running `/Users/4meta5/sunshine-protocol/sunshine-node/target/debug/examples/org`
Error: EventNotFound
```

**Comment by dvc94ch** [comment]
Solved
